<header class="wrapper top-bar">

    <div class="top-bar-brand">

        <div class="menu-icon" id="menu-toggle"></div>
        
        <div class="top-bar-item">
            <a href="#" class="logo">
                <img src="skin/img/logo.png" alt="" class="logo-img">
                <div class="title-6 logo-title">Auxílio IFES | Campus Colatina</div>
            </a>    
        </div>

    </div>

    <div class="top-bar-nav">

        <a href="#" class="top-bar-item top-bar-box">

            <div class="tb-box-item icon" >
                <i class="fa fa-envelope tb-box-icon"></i>
                <span class="badge">6</span>
            </div>

        </a>

        <div class="top-bar-item top-bar-box dropdown">

            <div class="tb-box-item" data-toggle="dropdown">
                <div class="user-name">Administrador <i class="fa fa-angle-down icon"></i></div>
                <img src="skin/img/user.png" alt="" class="user-image">
            </div>

            <div class="dropdown-menu">

              <ul class="nav dropdown-menu-list">

                <li class="active">
                  <a href="#">Home <i class="fa fa-home fa-fw icon"></i></a>
                </li>
                <li>
                  <a href="#">Library <i class="fa fa-book fa-fw icon"></i></a>
                </li>
                <li>
                  <a href="#">Applications <i class="fa fa-pencil fa-fw icon"></i></a>
                </li>
                <li>
                  <a href="#">Settings <i class="fa fa-cogs fa-fw icon"></i></a>
                </li>

              </ul>

              <button type="button" class="btn btn-danger btn-xs loguot">Sair</button>
            
            </div>

        </div>

    </div>

</header>