<nav class="menu" role="navigation">

	<div class="menu-item-dropdown">
		<div class="menu-item">Painel <i class="fa fa-home fa-fw fa-lg icon"></i></div>
		<ul class="menu-dropdown">
			<li><a class="item" href="">Painel</a></li>
			<li><a class="item" href="aluno">Alunos</a></li>
			<li><a class="item" href="#">Auxílios</a></li>
			<li><a class="item" href="#">Processos</a></li>
			<li><a class="item" href="#">Resultados</a></li>
		</ul>
	</div>

	<div class="menu-item-dropdown">
		<div class="menu-item">Aluno <i class="fa fa-user fa-fw fa-lg icon"></i></div>
		<ul class="menu-dropdown">
			<li><a class="item" href="?page=aluno">Gerenciar alunos</a></li>
			<li><a class="item" href="?page=aluno&action=cadastrar">Cadastrar aluno</a></li>
		</ul>
	</div>
	
	<div class="menu-item">Auxílios <i class="fa fa-cutlery fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Processos <i class="fa fa-file-text fa-fw fa-lg icon"></i></div>

	<div class="menu-item-dropdown">

		<div class="menu-item">Resultados <i class="fa fa-check-square-o fa-fw fa-lg icon"></i></div>

		<ul class="menu-dropdown">

			<li><a class="item" href="#">Teste</a></li>
			<li><a class="item" href="#">Teste</a></li>
			<li><a class="item" href="#">Teste</a></li>
			<li><a class="item" href="#">Teste</a></li>
			<li><a class="item" href="#">Teste</a></li>
			
		</ul>

	</div>

	<div class="menu-item">Critérios <i class="fa fa-list-ol fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Turmas <i class="fa fa-users fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Cursos <i class="fa fa-book fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Usuários <i class="fa fa-user fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Recursos <i class="fa fa-clipboard fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Pagamentos <i class="fa fa-usd fa-fw fa-lg icon"></i></div>
	<div class="menu-item">F.A.Q. <i class="fa fa-question fa-fw fa-lg icon"></i></div>
	<div class="menu-item">Configurações <i class="fa fa-cog fa-fw fa-lg icon"></i></div>

</nav>